In [ ]:
# Naive Bayes Algorithm
# The dataset consists of 3 columns - Population of a locality, No of active covid cases, and No of people vaccinated
# The algorithm classifies this data into 2 classes denoted as 1 (orange) and 0 (red) zones
# This Algorithm gives approx 70% accuracy
# Importing modules 

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [ ]:
# Importing datasets
dataset = pd.read_csv('Vaccination Data.csv')
X = dataset.iloc[:, [0,1,2]].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[  10000    2000    5000]
 [  15000    1000    4500]
 [   8000     908    2000]
 [  15000    3400    8000]
 [  18000    3700    8056]
 [  12000    2200    9000]
 [  16000    3000    8500]
 [  14000    5500    8800]
 [  17400    6255    8570]
 [ 125555    7545    9000]
 [3467897   94562   18000]
 [ 234567    8521    1234]
 [ 234567    8956    9876]
 [ 798546   21213     987]
 [  27600     563   17894]
 [  22000     562   15000]
 [   1200      10     600]
 [  50000     789    1000]
 [  60050    7984    2500]
 [   1020     789    3000]
 [   3060     752    1200]
 [   9000     784    5000]
 [  20000     258    4000]
 [  60000     951    8800]
 [  65320    4523    9200]
 [   1204     846     900]
 [  15000    7529   11000]
 [  30000     984   14000]
 [   5023     752    2400]
 [   7501     756    4000]
 [  90000     951   70000]
 [   5362     754    3000]
 [ 100000    8940   11000]
 [  20232     752   14000]
 [  30606     951   18000]
 [    606      88     400]
 [   3020     950    1200]
 

In [ ]:
# Transforming Data
# Dividing the dataset into train and test dataset
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 45)

In [ ]:
# Using Naive Bayes Algorithm
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
# Predicting using naive bayes algorithm
y_pred = classifier.predict(X_test)
print(X_test)
print(y_pred)

[[  4856    312   3800]
 [ 14000   5500   8800]
 [  8000    908   2000]
 [125555   7545   9000]
 [ 12000   2200   9000]
 [ 15000   7529  11000]
 [798546  21213    987]
 [ 90000   9870   8000]
 [ 10000   2000   5000]
 [  1020    789   3000]
 [  3060    752   1200]
 [ 60050   7984   2500]
 [  1200     10    600]]
[1 0 1 0 1 0 0 0 1 1 1 0 1]


In [ ]:
# Generating confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[6 4]
 [0 3]]


In [ ]:
# Finding the accuracy of our algorithm
accuracy_score(y_test,y_pred)

0.6923076923076923